import tjax

from imprl.modules.base import Module


@tjax.dataclass
class LinearModule(Module):
    """ A linear function whose weights are generated by some other module.
    """
    weight_module: Module = tjax.field(static=True)  # type: ignore

    def init(self, key, inputs):
        return self.weight_module.init(key, inputs)

    def apply(self, params, inputs):
        weights = self.weight_module.apply(params, inputs)
        return inputs @ weights
