from typing import Optional

import tjax

from imprl.modules.base import Module
from imprl.modules.features import Encoder


@tjax.dataclass
class LinearModule(Module):
    """ A linear function whose weights are generated by some other module.
    """
    weight_module: Module = tjax.field(static=True)  # type: ignore
    encoder: Optional[Encoder] = tjax.field(static=True, default=None)  # type: ignore

    def init(self, key, inputs):
        if self.encoder is not None:
            inputs = self.encoder.apply(inputs)
        return self.weight_module.init(key, inputs)

    def apply(self, params, inputs):
        if self.encoder is not None:
            inputs = self.encoder.apply(inputs)
        weights = self.weight_module.apply(params, inputs)
        return inputs @ weights
